// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: entries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEntry = `-- name: CreateEntry :one
INSERT INTO entries (
    amount, 
    account_id

) VALUES (
    $1, $2
) RETURNING entry_id, account_id, amount, created_at
`

type CreateEntryParams struct {
	Amount    int64       `json:"amount"`
	AccountID pgtype.Int8 `json:"account_id"`
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error) {
	row := q.db.QueryRow(ctx, createEntry, arg.Amount, arg.AccountID)
	var i Entry
	err := row.Scan(
		&i.EntryID,
		&i.AccountID,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const getEntry = `-- name: GetEntry :one
SELECT entry_id, account_id, amount, created_at FROM entries
WHERE entry_id = $1 LIMIT 1
`

func (q *Queries) GetEntry(ctx context.Context, entryID int64) (Entry, error) {
	row := q.db.QueryRow(ctx, getEntry, entryID)
	var i Entry
	err := row.Scan(
		&i.EntryID,
		&i.AccountID,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const listEntries = `-- name: ListEntries :many
SELECT entry_id, account_id, amount, created_at FROM entries
WHERE account_id = $1
ORDER BY entry_id
LIMIT $2
OFFSET $3
`

type ListEntriesParams struct {
	AccountID pgtype.Int8 `json:"account_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListEntries(ctx context.Context, arg ListEntriesParams) ([]Entry, error) {
	rows, err := q.db.Query(ctx, listEntries, arg.AccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.EntryID,
			&i.AccountID,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
